server:
  port: 9070

zuul:
  routes: ## 路由规则
    token:
      url: http://localhost:9090
    order:
      url: http://localhost:9080
  sensitive-headers: # Zuul默认会过滤一些头信息, 需要进行过滤设置, 如果为空表示所有header都可以通过
#  ignored-headers: #和sensitive-headers功能相反, 表示经过配置的才是可以放行的, 没有配置不能放行
