server:
  port: 9090

mybatis-plus:
  #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置控制台打印sql日志
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      id-type: auto  #0:数据库ID自增
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/db-oauth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456